frase = 'Curso em vídeo Python'
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[13:])
print(frase[1:15])
print(frase[1:15:2])
print(frase[1::2])
print(frase[::2])
print(frase.count('o'))
print(frase.upper().count('O'))
print(len(frase))
print(frase.replace('Python', 'Androide'))
print(frase.find('vídeo'))
print(frase.split())
div = frase.split()
print(div[0])
print(div[0][3])